Fix buffer type error in ROS2
ros-perception/vision_opencv pull request #235
Opened 2018-07-19 14:01 UTC by pantor

This fixes #213 for me.

2018-07-20 03:35 UTC, gaoethan commented
@pantor really thanks for your contribution, generally it has two methods to resolve this issue:

- option 1: make the `img_msg.data` is a byte-like object before giving it to `imgmsg_to_cv2()`
- option 2: make it a byte-like object in the` imgmsg_to_cv2()` just as you contributed in this PR.

Maybe the users are prone to forget to do option 1, so it makes sense to common it with option 2. but it's not necessary to convert again if the `img_msg.data` has already been a byte-like object before, so it's better add a condition checking to judge whether it's a byte-like object and then to convert or not in `imgmsg_to_cv2`, this also assure no overhead to those with the option 1 previously. thanks you !

2018-07-20 03:38 UTC, gaoethan requested changes

2018-07-20 03:38 UTC, gaoethan commented on cv_bridge/python/cv_bridge/core.py
> +        buf = np.asarray(img_msg.data, dtype=dtype)
It's better add a condition checking to `img_msg.data` before the real conversion to a byte-like object, thanks !

2018-07-25 08:50 UTC, pantor commented
Great, I've added a condition that checks for a list instance. I'm not sure if that covers everything a byte-like check would do.

I find option 2 better than 1. In my case, I use ROS2, convert a `cv::Mat` to a `sensor_msgs::msg::Image` in cpp, send it to another package and convert it back to a `cv::Mat` in python. I think cv_bridge should handle all conversion internally.

2018-07-26 08:17 UTC, gaoethan commented
lgtm. 
but a nit-pick: make the variable name `buf` be more accurate.

2018-07-26 08:19 UTC, merged